
local globals = {
	MASTER_VOLUME = 0.02,
	MUSIC_VOLUME = 0.55,
	DEFAULT_MUSIC_DURATION = 38.39,
	CROSSFADE_TIME = 0,
	
	LINE_SPACING = 36,
	INC_OFFSET = -15,
	
	PHYSICS_SCALE = 300,
	
	DRAW_DEBUG = true,
	INVENTORY_SLOTS = 7,
	
	MOVE_SPEED = 88,
	DROP_LEEWAY = 70,
}

return globals