
local globals = {
	MASTER_VOLUME = 0.35,
	MUSIC_VOLUME = 0.3,
	DEFAULT_MUSIC_DURATION = 174.69,
	CROSSFADE_TIME = 0,
	
	LINE_SPACING = 20,
	REPLY_LINE_SPACING = 38,
	INC_OFFSET = -15,
	
	PHYSICS_SCALE = 300,
	
	DRAW_DEBUG = true,
	INVENTORY_SLOTS = 5,
	
	MOVE_SPEED = 88,
	DROP_LEEWAY = 60,
	TALK_LEEWAY = 160,
	TILE_WIDTH = 1200,
	TILE_HEIGHT = 600,
	
	PORTRAIT_SPEED = 4,
	
	LOG_BUNDLE = 3,
	STICK_BUNDLE = 5,
	
	LINEAR_FUEL_DRAIN = -5,
	FUEL_DECAY_COEFF = -0.005,
}

return globals