--generalisable for other tile types, possbily also tiles in various stages of destruction prior to activation of excavator
local gn = 0 --no tile
local gy = 1 --yes tile

local tn = 0--0 --no trees
local tq = 0.25 --quarter trees
local th = 0.5 --half trees
local ty = 1 --yes trees
local td = 2 --double trees
local tt = 3 --triple trees
local tf = 4--4 --four times the trees

local def = {
	tiles = {
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gn,gn,gn,gn,gn,gn,gn,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gy,gn,gn,gn,gy,gn,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gy,gy,gy,gn,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gy,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gy,gy,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gy,gy,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gy,gy,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,},
		{gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,},
		{gy,gy,gy,gy,gy,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gn,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gn,gy,gy,gy,gy,gy,gy,gy,gy,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gn,gy,gy,gy,gy,gy,gy,gy,gn,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gn,gn,gy,gy,gy,gy,gy,gy,gn,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gn,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gn,gy,gy,gy,gy,gn,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gn,},
		{gn,gn,gn,gn,gy,gy,gy,gy,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gn,gn,gn,gn,gn,gy,gy,gy,gy,gy,gy,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gy,gn,gn,gn,gn,gn,gn,gy,gy,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
		{gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,gn,},
	},
	treeDensity = {
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,ty,tf,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,ty,tq,tn,tn,tn,tn,tn,tn,ty,ty,tf,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tq,ty,ty,tn,tn,tn,ty,ty,ty,ty,tf,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tq,ty,ty,tn,tn,ty,ty,ty,ty,ty,ty,ty,tn,tn,},
		{tn,ty,ty,tn,tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,},
		{tn,ty,ty,tn,tn,tn,tn,tn,ty,ty,ty,ty,tn,tn,tn,tn,ty,ty,tn,tn,},
		{tn,ty,ty,ty,tn,tn,tn,tn,ty,ty,ty,ty,tn,tn,tn,tn,ty,ty,ty,tn,},
		{ty,ty,ty,ty,tn,tn,tn,tn,tn,ty,ty,ty,tn,tn,tn,ty,ty,ty,ty,tn,},
		{ty,ty,ty,tn,tn,tn,tn,tn,tq,ty,ty,ty,tn,tn,tn,ty,ty,ty,ty,tn,},
		{ty,ty,ty,tn,tn,tn,tn,tn,tq,tq,ty,ty,ty,ty,ty,ty,ty,tn,tn,tn,},
		{ty,ty,ty,tn,tn,tn,tn,tn,tq,tq,ty,ty,ty,ty,ty,ty,ty,tn,tn,tn,},
		{ty,ty,ty,tn,tn,tn,tn,tn,tq,tq,ty,ty,ty,ty,ty,ty,tn,tn,tn,tn,},
		{ty,ty,tq,tn,tn,tn,tn,tn,tq,tq,ty,ty,ty,ty,ty,ty,tn,tn,tn,tn,},
		{ty,ty,tq,tn,tn,tn,tn,tn,tq,tq,ty,ty,ty,ty,ty,ty,tn,tn,tn,tn,},
		{ty,ty,tq,tq,tq,tq,tq,tq,tq,ty,ty,ty,ty,ty,ty,tn,tn,tn,tn,tn,},
		{ty,ty,ty,tq,tq,tq,tq,ty,ty,ty,ty,ty,ty,td,td,tn,tn,tn,tn,tn,},
		{ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,td,td,tn,tn,tn,tn,tn,},
		{ty,ty,ty,ty,ty,td,td,ty,ty,ty,ty,ty,ty,td,td,ty,ty,tn,tn,tn,},
		{tn,ty,ty,ty,ty,ty,td,td,td,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,tn,},
		{tn,ty,ty,ty,ty,ty,td,tf,tt,td,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,},
		{tn,ty,th,th,th,ty,td,tf,tf,td,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,},
		{tn,ty,th,th,th,ty,td,td,tt,ty,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,},
		{tn,ty,th,th,th,ty,ty,ty,td,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,tn,},
		{tn,ty,th,th,th,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,tn,},
		{ty,ty,ty,ty,ty,ty,ty,ty,ty,td,ty,tn,ty,ty,ty,ty,ty,td,td,td,},
		{ty,ty,ty,ty,ty,ty,ty,ty,ty,td,tn,tn,tn,ty,ty,ty,ty,td,td,td,},
		{ty,tn,tn,tn,th,ty,ty,ty,ty,ty,tn,tn,tn,ty,ty,ty,ty,ty,td,td,},
		{ty,tn,tn,tn,th,ty,ty,ty,tq,ty,tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,},
		{ty,tn,tn,tn,th,ty,ty,tq,tq,tq,tn,tn,tn,td,ty,ty,ty,ty,tn,ty,},
		{ty,tn,tn,tn,th,ty,ty,tq,tq,tq,tn,tn,tn,td,ty,ty,ty,ty,tn,ty,},
		{ty,tn,tn,tn,th,ty,ty,ty,ty,ty,tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,},
		{ty,tn,tn,tn,th,ty,ty,ty,ty,ty,ty,tn,ty,ty,ty,ty,ty,ty,ty,ty,},
		{ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,tn,tn,ty,ty,},
		{tn,ty,ty,ty,ty,ty,th,th,ty,ty,ty,ty,ty,ty,ty,tn,tn,tn,ty,ty,},
		{tn,tn,ty,ty,ty,ty,th,th,ty,ty,ty,ty,ty,ty,ty,tn,tn,tn,ty,ty,},
		{tn,tn,tn,ty,ty,ty,th,th,ty,ty,ty,ty,td,ty,ty,tn,tn,tn,ty,ty,},
		{tn,tn,tn,tn,ty,ty,th,th,ty,ty,ty,td,td,ty,ty,tn,tn,tn,ty,ty,},
		{tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,ty,ty,td,ty,ty,tn,tn,tn,ty,ty,},
		{tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,},
		{tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,ty,},
		{tn,tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,tn,ty,ty,ty,ty,ty,ty,ty,ty,},
		{tn,tn,tn,tn,ty,ty,ty,ty,ty,ty,ty,tn,ty,ty,ty,ty,ty,ty,ty,tn,},
		{tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,ty,tn,tn,ty,ty,ty,ty,ty,ty,tn,},
		{tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,ty,tn,tn,tn,tn,ty,ty,ty,ty,tn,},
		{tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,tn,tn,tn,tn,tn,ty,ty,ty,ty,tn,},
		{tn,tn,tn,tn,tn,tn,tn,ty,ty,ty,tn,tn,tn,tn,ty,ty,ty,ty,ty,tn,},
		{tn,tn,tn,tn,ty,ty,ty,ty,tn,tn,tn,tn,tn,tn,tn,tn,ty,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,ty,tn,tn,tn,tn,tn,tn,tn,tn,th,ty,ty,tn,tn,},
		{tn,tn,tn,tn,tn,tn,ty,tn,tn,tn,tn,tn,tn,tn,tq,th,th,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tq,tq,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
		{tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,tn,},
	},
	width = 20,
	height = 59,
	offsetX = -12, -- ODD NUMBERS NOT SUPPORTED
	offsetY = -32, -- ODD NUMBERS NOT SUPPORTED
}

return def
