return {
	{
		name = "build_button",
		file = "resources/images/build_button.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "build_button_highlight",
		file = "resources/images/build_button_highlight.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "build_button_open",
		file = "resources/images/build_button_open.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "close_button",
		file = "resources/images/close_button.png",
		form = "image",
		xScale = 2,
		yScale = 2,
		xOffset = 0,
		yOffset = 0,
	},
	{
		name = "close_button_highlight",
		file = "resources/images/close_button_highlight.png",
		form = "image",
		xScale = 2,
		yScale = 2,
		xOffset = 0,
		yOffset = 0,
	},
}