return {
	{
		name = "ground_11",
		file = "resources/images/tiles/grass_1.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0.5,
		yOffset = 0.375,
	},
	{
		name = "ground_11_crack_1",
		file = "resources/images/tiles/grass_1_crack_1.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0.5,
		yOffset = 0.375,
	},
	{
		name = "ground_11_crack_2",
		file = "resources/images/tiles/grass_1_crack_2.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0.5,
		yOffset = 0.375,
	},
	{
		name = "ground_11_crack_3",
		file = "resources/images/tiles/grass_1_crack_3.png",
		form = "image",
		xScale = 1,
		yScale = 1,
		xOffset = 0.5,
		yOffset = 0.375,
	},
}